terms:
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: CC0 1.0 Universal
    - id: http://creativecommons.org/licenses/by/4.0/
      term: Attribution 4.0 United States
    - id: http://creativecommons.org/licenses/by-nc/4.0/
      term: Attribution-NonCommercial 4.0 United States
    - id: http://creativecommons.org/licenses/by/3.0/us/
      term: Attribution 3.0 United States
    - id: http://creativecommons.org/licenses/by-nc/3.0/us/
      term: Attribution-NonCommercial 3.0 United States
    # - id: http://creativecommons.org/licenses/by-sa/3.0/us/
    #   term: Attribution-ShareAlike 3.0 United States
    # - id: http://creativecommons.org/licenses/by-nc-nd/3.0/us/
    #   term: Attribution-NonCommercial-NoDerivs 3.0 United States
    # - id: http://creativecommons.org/licenses/by-nc-nd/3.0/us/
    #   term: Attribution-NonCommercial-NoDerivs 3.0 United States
    # - id: http://creativecommons.org/licenses/by-nc-sa/3.0/us/
    #   term: Attribution-NonCommercial-ShareAlike 3.0 United States
    # - id: http://creativecommons.org/publicdomain/mark/1.0/
    #   term: Public Domain Mark 1.0
