# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  include Sufia::CollectionBehavior
  include Hydra::Collections::BasicMetadata
end
